version: '3'

services:
  app:
    build: ./express-mariadb-project
    container_name: express-app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=mydatabase
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=mydatabase
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
