version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: usersdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: letmein
    networks:
      - internalnet

  frontend:
    container_name: frontendcontainer
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000
    networks:
      - internalnet

  nodeapp:
    container_name: nodeappcontainer
    build: ./backend
    volumes:
      - $HOME/nodeapp:/code
      - /code/node_modules 
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: 'admin'
      DB_PASSWORD: 'letmein'
      DB_NAME: usersdb
      DB_CONNECTION_LIMIT: 20
      SERVER_PORT: 8000
    depends_on:
      - mysqldb
    networks:
      - internalnet

  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloakcontainer
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=mysql
      - DB_ADDR=mysqldb
      - DB_DATABASE=usersdb
      - DB_USER=admin
      - DB_PASSWORD=letmein
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
